<a href="https://colab.research.google.com/github/sangeerthP-10/Data_Science_Internship/blob/main/Data_science_internship_(day_15_%2C_day_16%2C_day_17).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df.shape

(150, 6)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [8]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

Handling Categorical Data(4 Types)

1.Manual Conversion

In [11]:
df1=df.copy(deep=True)
maping={'Iris-setosa':3,'Iris-versicolor':2,'Iris-virginica':1}
df1['Species']=df1['Species'].map(maping)

In [12]:
df1.head(80)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    1            5.1           3.5            1.4           0.2        3
1    2            4.9           3.0            1.4           0.2        3
2    3            4.7           3.2            1.3           0.2        3
3    4            4.6           3.1            1.5           0.2        3
4    5            5.0           3.6            1.4           0.2        3
..  ..            ...           ...            ...           ...      ...
75  76            6.6           3.0            4.4           1.4        2
76  77            6.8           2.8            4.8           1.4        2
77  78            6.7           3.0            5.0           1.7        2
78  79            6.0           2.9            4.5           1.5        2
79  80            5.7           2.6            3.5           1.0        2

[80 rows x 6 columns]

2.Label Encoder

In [13]:
df2=df.copy(deep=True)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df2['Species']=le.fit_transform(df2['Species'])
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [14]:
df2['Species']=le.inverse_transform(df2['Species'])
df2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
df2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

3. One Hot Encoding

In [16]:
df3=df.copy(deep=True)
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
ohe.fit_transform(df3[['Species']]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [17]:
df3['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

4.Dummy Variables

In [18]:
pd.get_dummies(df3["Species"],dtype=int)

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

Feature Scaling

In [19]:
from sklearn.preprocessing import MinMaxScaler
df4=df.copy(deep=True)
x4=df4.iloc[:,0:5]
mms=MinMaxScaler(feature_range=(0,1))#x_scaled=(x-xmin)//(x_max-xmin)
x4_scaled=Scaled=mms.fit_transform(x4)
x4_scaled

array([[0.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.00671141, 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.01342282, 0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.02013423, 0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.02684564, 0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.03355705, 0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.04026846, 0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.04697987, 0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.05369128, 0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.06040268, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.06711409, 0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.0738255 , 0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.08053691, 0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.08724832, 0.        , 0.41666667, 0.01694915, 0.        ],
       [0.09395973, 0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.10067114, 0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.10738255, 0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.11409396, 0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.12080537, 0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.12751678, 0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.13422819, 0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.1409396 , 0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.14765101, 0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.15436242, 0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.16107383, 0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.16778523, 0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.17449664, 0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.18120805, 0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.18791946, 0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.19463087, 0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.20134228, 0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.20805369, 0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.2147651 , 0.25      , 0.875     , 0.08474576, 0.        ],
       [0.22147651, 0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.22818792, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.23489933, 0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.24161074, 0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.24832215, 0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.25503356, 0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.26174497, 0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.26845638, 0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.27516779, 0.05555556, 0.125     , 0.05084746, 0.08333333],
       [0.28187919, 0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.2885906 , 0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.29530201, 0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.30201342, 0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.30872483, 0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.31543624, 0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.32214765, 0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.32885906, 0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.33557047, 0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.34228188, 0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.34899329, 0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.3557047 , 0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.36241611, 0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.36912752, 0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.37583893, 0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.38255034, 0.16666667, 0.16666667, 0.38983051, 0.375     ],
       [0.38926174, 0.63888889, 0.375     , 0.61016949, 0.5       ],
       [0.39597315, 0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.40268456, 0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.40939597, 0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.41610738, 0.47222222, 0.08333333, 0.50847458, 0.375     ],
       [0.42281879, 0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.4295302 , 0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.43624161, 0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.44295302, 0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.44966443, 0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.45637584, 0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.46308725, 0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.46979866, 0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.47651007, 0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.48322148, 0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.48993289, 0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.4966443 , 0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.5033557 , 0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.51006711, 0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.51677852, 0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.52348993, 0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.53020134, 0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.53691275, 0.33333333, 0.16666667, 0.47457627, 0.41666667],
       [0.54362416, 0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.55033557, 0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.55704698, 0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.56375839, 0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.5704698 , 0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.57718121, 0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.58389262, 0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.59060403, 0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.59731544, 0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.60402685, 0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.61073826, 0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.61744966, 0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.62416107, 0.19444444, 0.125     , 0.38983051, 0.375     ],
       [0.63087248, 0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.63758389, 0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.6442953 , 0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.65100671, 0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.65771812, 0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.66442953, 0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.67114094, 0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.67785235, 0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.68456376, 0.77777778, 0.41666667, 0.83050847, 0.83333333],
       [0.69127517, 0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.69798658, 0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.70469799, 0.91666667, 0.41666667, 0.94915254, 0.83333333],
       [0.7114094 , 0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.71812081, 0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.72483221, 0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.73154362, 0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.73825503, 0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.74496644, 0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.75167785, 0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.75838926, 0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.76510067, 0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.77181208, 0.58333333, 0.5       , 0.72881356, 0.91666667],
       [0.77852349, 0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.7852349 , 0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.79194631, 0.94444444, 0.25      , 1.        , 0.91666667],
       [0.79865772, 0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.80536913, 0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.81208054, 0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.81879195, 0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.82550336, 0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.83221477, 0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.83892617, 0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.84563758, 0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.85234899, 0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.8590604 , 0.58333333, 0.33333333, 0.77966102, 0.83333333],
       [0.86577181, 0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.87248322, 0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [0.87919463, 1.        , 0.75      , 0.91525424, 0.79166667],
       [0.88590604, 0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.89261745, 0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.89932886, 0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.90604027, 0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.91275168, 0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.91946309, 0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.9261745 , 0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.93288591, 0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.93959732, 0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.94630872, 0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.95302013, 0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.95973154, 0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.96644295, 0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.97315436, 0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.97986577, 0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.98657718, 0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.99328859, 0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [1.        , 0.44444444, 0.41666667, 0.69491525, 0.70833333]])

In [20]:
from sklearn.preprocessing import StandardScaler
df5=df.copy(deep=True)
x5=df5.iloc[:,0:5]
scalerr=StandardScaler()
x5_scaled=scalerr.fit_transform(x5)#value is subtracted by mean and divided by standard Deviation
x5_scaled

array([[-1.72054204e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.69744751e+00, -1.14301691e+00, -1.24957601e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.67435299e+00, -1.38535265e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-1.65125846e+00, -1.50652052e+00,  1.06445364e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.62816394e+00, -1.02184904e+00,  1.26346019e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.60506942e+00, -5.37177559e-01,  1.95766909e+00,
        -1.17067529e+00, -1.05003079e+00],
       [-1.58197489e+00, -1.50652052e+00,  8.00654259e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-1.55888037e+00, -1.02184904e+00,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.53578584e+00, -1.74885626e+00, -3.56360566e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.51269132e+00, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-1.48959680e+00, -5.37177559e-01,  1.49486315e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-1.46650227e+00, -1.26418478e+00,  8.00654259e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.44340775e+00, -1.26418478e+00, -1.24957601e-01,
        -1.34127240e+00, -1.44444970e+00],
       [-1.42031323e+00, -1.87002413e+00, -1.24957601e-01,
        -1.51186952e+00, -1.44444970e+00],
       [-1.39721870e+00, -5.25060772e-02,  2.18907205e+00,
        -1.45500381e+00, -1.31297673e+00],
       [-1.37412418e+00, -1.73673948e-01,  3.11468391e+00,
        -1.28440670e+00, -1.05003079e+00],
       [-1.35102965e+00, -5.37177559e-01,  1.95766909e+00,
        -1.39813811e+00, -1.05003079e+00],
       [-1.32793513e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.18150376e+00],
       [-1.30484061e+00, -1.73673948e-01,  1.72626612e+00,
        -1.17067529e+00, -1.18150376e+00],
       [-1.28174608e+00, -9.00681170e-01,  1.72626612e+00,
        -1.28440670e+00, -1.18150376e+00],
       [-1.25865156e+00, -5.37177559e-01,  8.00654259e-01,
        -1.17067529e+00, -1.31297673e+00],
       [-1.23555703e+00, -9.00681170e-01,  1.49486315e+00,
        -1.28440670e+00, -1.05003079e+00],
       [-1.21246251e+00, -1.50652052e+00,  1.26346019e+00,
        -1.56873522e+00, -1.31297673e+00],
       [-1.18936799e+00, -9.00681170e-01,  5.69251294e-01,
        -1.17067529e+00, -9.18557817e-01],
       [-1.16627346e+00, -1.26418478e+00,  8.00654259e-01,
        -1.05694388e+00, -1.31297673e+00],
       [-1.14317894e+00, -1.02184904e+00, -1.24957601e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.12008441e+00, -1.02184904e+00,  8.00654259e-01,
        -1.22754100e+00, -1.05003079e+00],
       [-1.09698989e+00, -7.79513300e-01,  1.03205722e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-1.07389537e+00, -7.79513300e-01,  8.00654259e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.05080084e+00, -1.38535265e+00,  3.37848329e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.02770632e+00, -1.26418478e+00,  1.06445364e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.00461179e+00, -5.37177559e-01,  8.00654259e-01,
        -1.28440670e+00, -1.05003079e+00],
       [-9.81517269e-01, -7.79513300e-01,  2.42047502e+00,
        -1.28440670e+00, -1.44444970e+00],
       [-9.58422745e-01, -4.16009689e-01,  2.65187798e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-9.35328221e-01, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-9.12233697e-01, -1.02184904e+00,  3.37848329e-01,
        -1.45500381e+00, -1.31297673e+00],
       [-8.89139173e-01, -4.16009689e-01,  1.03205722e+00,
        -1.39813811e+00, -1.31297673e+00],
       [-8.66044649e-01, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-8.42950125e-01, -1.74885626e+00, -1.24957601e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-8.19855601e-01, -9.00681170e-01,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-7.96761077e-01, -1.02184904e+00,  1.03205722e+00,
        -1.39813811e+00, -1.18150376e+00],
       [-7.73666553e-01, -1.62768839e+00, -1.74477836e+00,
        -1.39813811e+00, -1.18150376e+00],
       [-7.50572030e-01, -1.74885626e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-7.27477506e-01, -1.02184904e+00,  1.03205722e+00,
        -1.22754100e+00, -7.87084847e-01],
       [-7.04382982e-01, -9.00681170e-01,  1.72626612e+00,
        -1.05694388e+00, -1.05003079e+00],
       [-6.81288458e-01, -1.26418478e+00, -1.24957601e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-6.58193934e-01, -9.00681170e-01,  1.72626612e+00,
        -1.22754100e+00, -1.31297673e+00],
       [-6.35099410e-01, -1.50652052e+00,  3.37848329e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-6.12004886e-01, -6.58345429e-01,  1.49486315e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-5.88910362e-01, -1.02184904e+00,  5.69251294e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-5.65815838e-01,  1.40150837e+00,  3.37848329e-01,
         5.35295827e-01,  2.64698913e-01],
       [-5.42721314e-01,  6.74501145e-01,  3.37848329e-01,
         4.21564419e-01,  3.96171883e-01],
       [-5.19626790e-01,  1.28034050e+00,  1.06445364e-01,
         6.49027235e-01,  3.96171883e-01],
       [-4.96532266e-01, -4.16009689e-01, -1.74477836e+00,
         1.37235899e-01,  1.33225943e-01],
       [-4.73437742e-01,  7.95669016e-01, -5.87763531e-01,
         4.78430123e-01,  3.96171883e-01],
       [-4.50343218e-01, -1.73673948e-01, -5.87763531e-01,
         4.21564419e-01,  1.33225943e-01],
       [-4.27248694e-01,  5.53333275e-01,  5.69251294e-01,
         5.35295827e-01,  5.27644853e-01],
       [-4.04154170e-01, -1.14301691e+00, -1.51337539e+00,
        -2.60824029e-01, -2.61192967e-01],
       [-3.81059646e-01,  9.16836886e-01, -3.56360566e-01,
         4.78430123e-01,  1.33225943e-01],
       [-3.57965122e-01, -7.79513300e-01, -8.19166497e-01,
         8.03701950e-02,  2.64698913e-01],
       [-3.34870598e-01, -1.02184904e+00, -2.43898725e+00,
        -1.47092621e-01, -2.61192967e-01],
       [-3.11776074e-01,  6.86617933e-02, -1.24957601e-01,
         2.50967307e-01,  3.96171883e-01],
       [-2.88681550e-01,  1.89829664e-01, -1.97618132e+00,
         1.37235899e-01, -2.61192967e-01],
       [-2.65587026e-01,  3.10997534e-01, -3.56360566e-01,
         5.35295827e-01,  2.64698913e-01],
       [-2.42492502e-01, -2.94841818e-01, -3.56360566e-01,
        -9.02269170e-02,  1.33225943e-01],
       [-2.19397978e-01,  1.03800476e+00,  1.06445364e-01,
         3.64698715e-01,  2.64698913e-01],
       [-1.96303454e-01, -2.94841818e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [-1.73208930e-01, -5.25060772e-02, -8.19166497e-01,
         1.94101603e-01, -2.61192967e-01],
       [-1.50114406e-01,  4.32165405e-01, -1.97618132e+00,
         4.21564419e-01,  3.96171883e-01],
       [-1.27019882e-01, -2.94841818e-01, -1.28197243e+00,
         8.03701950e-02, -1.29719997e-01],
       [-1.03925358e-01,  6.86617933e-02,  3.37848329e-01,
         5.92161531e-01,  7.90590793e-01],
       [-8.08308339e-02,  3.10997534e-01, -5.87763531e-01,
         1.37235899e-01,  1.33225943e-01],
       [-5.77363100e-02,  5.53333275e-01, -1.28197243e+00,
         6.49027235e-01,  3.96171883e-01],
       [-3.46417860e-02,  3.10997534e-01, -5.87763531e-01,
         5.35295827e-01,  1.75297293e-03],
       [-1.15472620e-02,  6.74501145e-01, -3.56360566e-01,
         3.07833011e-01,  1.33225943e-01],
       [ 1.15472620e-02,  9.16836886e-01, -1.24957601e-01,
         3.64698715e-01,  2.64698913e-01],
       [ 3.46417860e-02,  1.15917263e+00, -5.87763531e-01,
         5.92161531e-01,  2.64698913e-01],
       [ 5.77363100e-02,  1.03800476e+00, -1.24957601e-01,
         7.05892939e-01,  6.59117823e-01],
       [ 8.08308339e-02,  1.89829664e-01, -3.56360566e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 1.03925358e-01, -1.73673948e-01, -1.05056946e+00,
        -1.47092621e-01, -2.61192967e-01],
       [ 1.27019882e-01, -4.16009689e-01, -1.51337539e+00,
         2.35044910e-02, -1.29719997e-01],
       [ 1.50114406e-01, -4.16009689e-01, -1.51337539e+00,
        -3.33612130e-02, -2.61192967e-01],
       [ 1.73208930e-01, -5.25060772e-02, -8.19166497e-01,
         8.03701950e-02,  1.75297293e-03],
       [ 1.96303454e-01,  1.89829664e-01, -8.19166497e-01,
         7.62758643e-01,  5.27644853e-01],
       [ 2.19397978e-01, -5.37177559e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 2.42492502e-01,  1.89829664e-01,  8.00654259e-01,
         4.21564419e-01,  5.27644853e-01],
       [ 2.65587026e-01,  1.03800476e+00,  1.06445364e-01,
         5.35295827e-01,  3.96171883e-01],
       [ 2.88681550e-01,  5.53333275e-01, -1.74477836e+00,
         3.64698715e-01,  1.33225943e-01],
       [ 3.11776074e-01, -2.94841818e-01, -1.24957601e-01,
         1.94101603e-01,  1.33225943e-01],
       [ 3.34870598e-01, -4.16009689e-01, -1.28197243e+00,
         1.37235899e-01,  1.33225943e-01],
       [ 3.57965122e-01, -4.16009689e-01, -1.05056946e+00,
         3.64698715e-01,  1.75297293e-03],
       [ 3.81059646e-01,  3.10997534e-01, -1.24957601e-01,
         4.78430123e-01,  2.64698913e-01],
       [ 4.04154170e-01, -5.25060772e-02, -1.05056946e+00,
         1.37235899e-01,  1.75297293e-03],
       [ 4.27248694e-01, -1.02184904e+00, -1.74477836e+00,
        -2.60824029e-01, -2.61192967e-01],
       [ 4.50343218e-01, -2.94841818e-01, -8.19166497e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 4.73437742e-01, -1.73673948e-01, -1.24957601e-01,
         2.50967307e-01,  1.75297293e-03],
       [ 4.96532266e-01, -1.73673948e-01, -3.56360566e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 5.19626790e-01,  4.32165405e-01, -3.56360566e-01,
         3.07833011e-01,  1.33225943e-01],
       [ 5.42721314e-01, -9.00681170e-01, -1.28197243e+00,
        -4.31421141e-01, -1.29719997e-01],
       [ 5.65815838e-01, -1.73673948e-01, -5.87763531e-01,
         1.94101603e-01,  1.33225943e-01],
       [ 5.88910362e-01,  5.53333275e-01,  5.69251294e-01,
         1.27454998e+00,  1.71090158e+00],
       [ 6.12004886e-01, -5.25060772e-02, -8.19166497e-01,
         7.62758643e-01,  9.22063763e-01],
       [ 6.35099410e-01,  1.52267624e+00, -1.24957601e-01,
         1.21768427e+00,  1.18500970e+00],
       [ 6.58193934e-01,  5.53333275e-01, -3.56360566e-01,
         1.04708716e+00,  7.90590793e-01],
       [ 6.81288458e-01,  7.95669016e-01, -1.24957601e-01,
         1.16081857e+00,  1.31648267e+00],
       [ 7.04382982e-01,  2.12851559e+00, -1.24957601e-01,
         1.61574420e+00,  1.18500970e+00],
       [ 7.27477506e-01, -1.14301691e+00, -1.28197243e+00,
         4.21564419e-01,  6.59117823e-01],
       [ 7.50572030e-01,  1.76501198e+00, -3.56360566e-01,
         1.44514709e+00,  7.90590793e-01],
       [ 7.73666553e-01,  1.03800476e+00, -1.28197243e+00,
         1.16081857e+00,  7.90590793e-01],
       [ 7.96761077e-01,  1.64384411e+00,  1.26346019e+00,
         1.33141568e+00,  1.71090158e+00],
       [ 8.19855601e-01,  7.95669016e-01,  3.37848329e-01,
         7.62758643e-01,  1.05353673e+00],
       [ 8.42950125e-01,  6.74501145e-01, -8.19166497e-01,
         8.76490051e-01,  9.22063763e-01],
       [ 8.66044649e-01,  1.15917263e+00, -1.24957601e-01,
         9.90221459e-01,  1.18500970e+00],
       [ 8.89139173e-01, -1.73673948e-01, -1.28197243e+00,
         7.05892939e-01,  1.05353673e+00],
       [ 9.12233697e-01, -5.25060772e-02, -5.87763531e-01,
         7.62758643e-01,  1.57942861e+00],
       [ 9.35328221e-01,  6.74501145e-01,  3.37848329e-01,
         8.76490051e-01,  1.44795564e+00],
       [ 9.58422745e-01,  7.95669016e-01, -1.24957601e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 9.81517269e-01,  2.24968346e+00,  1.72626612e+00,
         1.67260991e+00,  1.31648267e+00],
       [ 1.00461179e+00,  2.24968346e+00, -1.05056946e+00,
         1.78634131e+00,  1.44795564e+00],
       [ 1.02770632e+00,  1.89829664e-01, -1.97618132e+00,
         7.05892939e-01,  3.96171883e-01],
       [ 1.05080084e+00,  1.28034050e+00,  3.37848329e-01,
         1.10395287e+00,  1.44795564e+00],
       [ 1.07389537e+00, -2.94841818e-01, -5.87763531e-01,
         6.49027235e-01,  1.05353673e+00],
       [ 1.09698989e+00,  2.24968346e+00, -5.87763531e-01,
         1.67260991e+00,  1.05353673e+00],
       [ 1.12008441e+00,  5.53333275e-01, -8.19166497e-01,
         6.49027235e-01,  7.90590793e-01],
       [ 1.14317894e+00,  1.03800476e+00,  5.69251294e-01,
         1.10395287e+00,  1.18500970e+00],
       [ 1.16627346e+00,  1.64384411e+00,  3.37848329e-01,
         1.27454998e+00,  7.90590793e-01],
       [ 1.18936799e+00,  4.32165405e-01, -5.87763531e-01,
         5.92161531e-01,  7.90590793e-01],
       [ 1.21246251e+00,  3.10997534e-01, -1.24957601e-01,
         6.49027235e-01,  7.90590793e-01],
       [ 1.23555703e+00,  6.74501145e-01, -5.87763531e-01,
         1.04708716e+00,  1.18500970e+00],
       [ 1.25865156e+00,  1.64384411e+00, -1.24957601e-01,
         1.16081857e+00,  5.27644853e-01],
       [ 1.28174608e+00,  1.88617985e+00, -5.87763531e-01,
         1.33141568e+00,  9.22063763e-01],
       [ 1.30484061e+00,  2.49201920e+00,  1.72626612e+00,
         1.50201279e+00,  1.05353673e+00],
       [ 1.32793513e+00,  6.74501145e-01, -5.87763531e-01,
         1.04708716e+00,  1.31648267e+00],
       [ 1.35102965e+00,  5.53333275e-01, -5.87763531e-01,
         7.62758643e-01,  3.96171883e-01],
       [ 1.37412418e+00,  3.10997534e-01, -1.05056946e+00,
         1.04708716e+00,  2.64698913e-01],
       [ 1.39721870e+00,  2.24968346e+00, -1.24957601e-01,
         1.33141568e+00,  1.44795564e+00],
       [ 1.42031323e+00,  5.53333275e-01,  8.00654259e-01,
         1.04708716e+00,  1.57942861e+00],
       [ 1.44340775e+00,  6.74501145e-01,  1.06445364e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 1.46650227e+00,  1.89829664e-01, -1.24957601e-01,
         5.92161531e-01,  7.90590793e-01],
       [ 1.48959680e+00,  1.28034050e+00,  1.06445364e-01,
         9.33355755e-01,  1.18500970e+00],
       [ 1.51269132e+00,  1.03800476e+00,  1.06445364e-01,
         1.04708716e+00,  1.57942861e+00],
       [ 1.53578584e+00,  1.28034050e+00,  1.06445364e-01,
         7.62758643e-01,  1.44795564e+00],
       [ 1.55888037e+00, -5.25060772e-02, -8.19166497e-01,
         7.62758643e-01,  9.22063763e-01],
       [ 1.58197489e+00,  1.15917263e+00,  3.37848329e-01,
         1.21768427e+00,  1.44795564e+00],
       [ 1.60506942e+00,  1.03800476e+00,  5.69251294e-01,
         1.10395287e+00,  1.71090158e+00],
       [ 1.62816394e+00,  1.03800476e+00, -1.24957601e-01,
         8.19624347e-01,  1.44795564e+00],
       [ 1.65125846e+00,  5.53333275e-01, -1.28197243e+00,
         7.05892939e-01,  9.22063763e-01],
       [ 1.67435299e+00,  7.95669016e-01, -1.24957601e-01,
         8.19624347e-01,  1.05353673e+00],
       [ 1.69744751e+00,  4.32165405e-01,  8.00654259e-01,
         9.33355755e-01,  1.44795564e+00],
       [ 1.72054204e+00,  6.86617933e-02, -1.24957601e-01,
         7.62758643e-01,  7.90590793e-01]])

In [25]:
from sklearn.preprocessing import Binarizer
df6=df.copy(deep=True)
x6=df6.iloc[:,0:5]
bin=Binarizer(threshold=3)# if value below threshold value is 0 else 1
x6_scale=bin.fit_transform(x6)
x6_scale

array([[0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.]])