<a href="https://colab.research.google.com/github/sangeerthP-10/Data_Science_Internship/blob/main/Data_science_internship_(day_13).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as mp

In [2]:
df=pd.read_csv("Iris_1.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
df.shape

(150, 6)

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     148.000000    147.000000     146.000000    144.000000
mean    75.500000       5.858784      3.050340       3.820548      1.235417
std     43.445368       0.822716      0.435949       1.747586      0.756461
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.400000      1.350000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  146 non-null    float64
 4   PetalWidthCm   144 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [6]:
df1=df.copy(deep=True)

In [11]:
df1.isna().sum()

Id               0
SepalLengthCm    2
SepalWidthCm     3
PetalLengthCm    4
PetalWidthCm     6
Species          0
dtype: int64

In [8]:
df.head(30)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            NaN           NaN  Iris-setosa
6    7            NaN           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           NaN            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            NaN           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            NaN           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           NaN            1.7           0.2  Iris-setosa
21  22            5.1           3.7            NaN           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           NaN  Iris-setosa
24  25            4.8           3.4            1.9           NaN  Iris-setosa
25  26            5.0           3.0            1.6           NaN  Iris-setosa
26  27            5.0           3.4            1.6           NaN  Iris-setosa
27  28            5.2           3.5            1.5           NaN  Iris-setosa
28  29            5.2           NaN            NaN           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa

In [13]:
median1=df['SepalLengthCm'].median()

In [20]:
df1['SepalLengthCm'] = df1['SepalLengthCm'].fillna(median1)

In [21]:
df1.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     3
PetalLengthCm    4
PetalWidthCm     6
Species          0
dtype: int64

In [22]:
df1.head(30)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            NaN           NaN  Iris-setosa
6    7            5.8           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           NaN            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            5.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            NaN           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           NaN            1.7           0.2  Iris-setosa
21  22            5.1           3.7            NaN           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           NaN  Iris-setosa
24  25            4.8           3.4            1.9           NaN  Iris-setosa
25  26            5.0           3.0            1.6           NaN  Iris-setosa
26  27            5.0           3.4            1.6           NaN  Iris-setosa
27  28            5.2           3.5            1.5           NaN  Iris-setosa
28  29            5.2           NaN            NaN           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa